### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna-examples#117]
## Motivation

Related to https://github.com/optuna/optuna/issues/3021. 
The current master of `optuna` stopped Python 3.6 support for integration modules and optuna-examples.
For further details, please refer to as can be seen in https://github.com/optuna/optuna/issues/3021#issuecomment-1129545028.

## Description

Please remove the Python 3.6 execution in following CI:

- [ ] base.yml
- [ ] catboost.yml
- [ ] chainer.yml
- [ ] dask_ml.yml
- [ ] hiplot.yml
- [ ] hydra.yml
- [ ] lightgbm.yml
- [ ] multi_objective.yml
- [ ] mxnet.yml
- [ ] pytorch.yml
- [ ] ray.yml
- [ ] rl.yml
- [ ] samplers.yml
- [ ] skimage.yml
- [ ] sklearn.yml
- [ ] visualization.yml
- [ ] wandb.yml
- [ ] xgboost.yml

In concrete, we can simply remove '3.6' from the `python-version` list:

```yaml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
```

In addition, we can also remove the conditional branch regarding Python 3.6 if exists.
